version: '3.8'

services:
  web:
    build:
      context: ./web
    container_name: library_web
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  bot:
    build:
      context: ./bot
    container_name: telegram_bot
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: aifu_library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:

